config/routes.rb
DevelopmentActivityApp::Application.routes.draw do

  resources :skill_groups

  resources :users_linemanagers

  resources :role_skills

  resources :dev_activities

  resources :roles do 
    resources :role_skills
  end

  resources :user_skills

  get "pages/AdminDashboard"
  get "pages/LineManagerDashboard"

  resources :skills

  get "mainpage/index"
  root :to => "mainpage#index"

  devise_for :users,
            :controllers => {:registrations => "my_devise/registrations"}

  resources :users do

    collection do
      get 'linemanager_team'
      match 'linemanager_skill_search' => 'users#linemanager_skill_search', via: [:get, :post], as: :linemanager_skill_search
    end

    resources :dev_activities

    resources :user_skills

    resources :linemanagers

    resources :users_linemanagers do
        collection do
          get 'user_search'
        end
    end

    patch 'update_password', on: :collection
    get 'edit_password', on: :member

  end

end

app/models/users_linemanager.rb
class UsersLinemanager < ActiveRecord::Base

	belongs_to :linemanager
	belongs_to :user

end

app/controllers/users_linemanagers_controller.rb
class UsersLinemanagersController < ApplicationController
  #before_action :set_users_linemanager, only: [:show, :edit, :update, :destroy]
  before_action :set_linemanager, only: [:index, :show]


  def user_search
    @search = User.search(params[:q])
    @users = @search.result #.includes(:user)
  end

  # GET /users_linemanagers
  # GET /users_linemanagers.json
  def index
    
  end

  # GET /users_linemanagers/1
  # GET /users_linemanagers/1.json
  def show
  end

  # GET /users_linemanagers/new
  def new
    @search = User.search(params[:q])
    @users = @search.result #.includes(:user)
    @users_linemanager = UsersLinemanager.new
  end

  # GET /users_linemanagers/1/edit
  def edit
  end

  # POST /users_linemanagers
  # POST /users_linemanagers.json
  def create
    @users_linemanager = UsersLinemanager.new(users_linemanager_params)

    respond_to do |format|
      if @users_linemanager.save
        format.html { redirect_to :back, notice: "You are now Linemanaging #{@users_linemanager.user.first_name} #{@users_linemanager.user.surname}." }
        format.json { render action: 'show', status: :created, location: @users_linemanager }
      else
        format.html { render action: 'new' }
        format.json { render json: @users_linemanager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_linemanagers/1
  # PATCH/PUT /users_linemanagers/1.json
  def update
    respond_to do |format|
      if @users_linemanager.update(users_linemanager_params)
        format.html { redirect_to @users_linemanager, notice: 'Users linemanager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @users_linemanager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_linemanagers/1
  # DELETE /users_linemanagers/1.json
  def destroy
    @users_linemanager.destroy
    respond_to do |format|
      format.html { redirect_to users_linemanagers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_linemanager
      @users_linemanager = UsersLinemanager.find(params[:id])
    end

    def set_linemanager
      @user = current_user
      @linemanager = Linemanager.where("user_id = @user.id")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_linemanager_params
      params.require(:users_linemanager).permit(:linemanager_id, :user_id)
    end
end

app/helpers/users_linemanagers_helper.rb
module UsersLinemanagersHelper
end

app/views/users_linemanagers/_form.html.erb
<%= form_for @users_linemanager  do |f| %>

		<%= f.hidden_field :user_id, :value => user.id %>

		<%= f.hidden_field :linemanager_id, :value => current_user.id %>

    <div class="actions">
  		<%= f.submit "Linemanage", class: "nav_button" %>
    </div>

<% end %>

app/views/users_linemanagers/edit.html.erb
<h1>Editing users_linemanager</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_linemanager %> |
<%= link_to 'Back', users_linemanagers_path %>

app/views/users_linemanagers/index.html.erb
<h1>Listing users_linemanagers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users_linemanagers.each do |users_linemanager| %>
      <tr>
        <td><%= link_to 'Show', users_linemanager %></td>
        <td><%= link_to 'Edit', edit_users_linemanager_path(users_linemanager) %></td>
        <td><%= link_to 'Destroy', users_linemanager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users linemanager', new_users_linemanager_path %>

app/views/users_linemanagers/new.html.erb
<div class="outer-block">
    <div class="inner-block">

    <h2>Add Team Members</h2>

    <%= search_form_for @search, url: new_user_users_linemanager_path do |f| %>

      <%= f.label :surname_cont, "Search by Surname" %>
      <%= f.search_field :surname_cont %>

      <%= f.label :first_name_cont, "Search by First Name" %>
      <%= f.search_field :first_name_cont %>

    	<div class="actions"><%= f.submit "Search", class: "nav_button" %></div>

	  <% end %> 

    <table>
      <thead>
        <tr>
          <th><%= sort_link(@search, :first_name) %></th>
          <th><%= sort_link(@search, :surname) %></th>
          <th></th>
          <th><%= "Linemanager" %></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>  
            <td><%= user.surname %></td> 
            <td><%= link_to 'Show', user %></td>
            
            <% @linemanaged = UsersLinemanager.where(:user_id => user.id).any? %> 

            <td><% if @linemanaged == false %>

            		  <%= form_for @users_linemanager  do |f| %>

                  	<%= f.hidden_field :user_id, :value => user.id %>

                  	<%= f.hidden_field :linemanager_id, :value => current_user.id %>

                    <div class="actions">
                      <%= f.submit "Linemanage", class: "nav_button" %>
                    </div>

                	<% end %>

                <% else @linemanaged == true %>

                	<% @linemanaged_by = UsersLinemanager.find_by(:user_id => user.id)%>
                	<% @linemanager = Linemanager.find_by(:user_id => @linemanaged_by.linemanager_id) %>
                	<%= "Linemanaged by #{@linemanager.user.first_name} #{@linemanager.user.surname}"  %>

                <% end %>
            </td>        
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

  </div>
</div>

app/views/users_linemanagers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_users_linemanager_path(@users_linemanager) %> |
<%= link_to 'Back', users_linemanagers_path %>