config/routes.rb
DevelopmentActivityApp::Application.routes.draw do

  resources :skill_groups

  resources :users_linemanagers

  resources :role_skills

  resources :dev_activities

  resources :roles do 
    resources :role_skills
  end

  resources :user_skills

  get "pages/AdminDashboard"
  get "pages/LineManagerDashboard"

  resources :skills

  get "mainpage/index"
  root :to => "mainpage#index"

  devise_for :users,
            :controllers => {:registrations => "my_devise/registrations"}

  resources :users do

    collection do
      get 'linemanager_team'
      match 'linemanager_skill_search' => 'users#linemanager_skill_search', via: [:get, :post], as: :linemanager_skill_search
    end

    resources :dev_activities

    resources :user_skills

    resources :linemanagers

    resources :users_linemanagers do
        collection do
          get 'user_search'
        end
    end

    patch 'update_password', on: :collection
    get 'edit_password', on: :member

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #A user can have many dev activities, their dev activities will be deleted if the user is deleted
  belongs_to :role
  has_many :dev_activities, dependent: :destroy
  has_many :user_skills, dependent: :destroy
  has_many :skills, :through => :user_skills
  has_one  :linemanager
  has_many :users_linemanagers
  has_many :linemanagers, :through => :users_linemanagers

  accepts_nested_attributes_for :users_linemanagers,
      :reject_if => lambda { |attrs| attrs.all? { |key, value| value.blank? } }, :allow_destroy => true



  #For a user to sign up they much record there first name, surname and workgroup (and email - but that is also username)
  validates :first_name,  :presence => true
  validates :surname,  :presence => true
  validates :role_id,  :presence => true

        #This is temporary code to encrypt passwords - will be removed when all users are in database

      def valid_password?(password)
        if self.password_temp.present?
          if password == self.password_temp
            self.password = password
            self.password_temp = nil
            self.save!
            true
          else
            false
          end
        else
          super
        end
      end

      def reset_password!(*args)
        self.password_temp = nil
        super
      end

      #Temp as above - this is the command to run
      #users = User.where("password_temp"!=''); users.each do |i|; i.valid_password?(i.password_temp); end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_skills, only: [:show, :destroy]
  before_action :find_roles, only: [:show, :create, :edit]
  #before_action :set_linemanager, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @search = User.search(params[:q])
    @users = @search.result #.includes(:user)
  end

  def linemanager_skill_search
    @q = User.search(params[:q])
    if params[:q]
      @skill_id = params[:q]['user_skills_skill_id_eq']
    else
    end
    @users = @q.result.includes(:user_skills, :skills) #.includes(:user)

  end
#@q = Site.joins(:site_management).where('site_managements.management_id' => @owner.id).search(params[:q])
  # GET /users/1
  # GET /users/1.json
  def show
    find_roles
  end

  def linemanager_team
    @user = current_user 
    @linemanager = Linemanager.find_by(:user_id => @user.id) 
    @linemanaged_team = User.joins(:users_linemanagers).where('users_linemanagers.linemanager_id' => @linemanager.id).to_a
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update_with_password(password_params)
      sign_in @user, :bypass => true
      redirect_to @user, notice: 'Your password was successfully changed.'
    else
      render "edit_password"
    end
  end

  # POST /users
  # POST /users.json
  # Creates the user - 
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # Currently not in use - will change this to redirect to mainpage when utilised
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Finds the user when an ID is provided

    def find_skills
      @user = User.find(params[:id])
      @user_skill = UserSkill.where("user_id = @user.id")
    end

    def find_roles
      @user = User.find(params[:id])
      @role = Role.where("id = @user.role_id")
    end

    def set_linemanager
      @linemanaged_by = UsersLinemanager.find_by(:user_id => @user.id)
      if @linemanaged_by
        @linemanager = Linemanager.find_by(:user_id => @linemanaged_by.linemanager_id) 
      else
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # Any new parameters need to be added here as well as in the user controller to have them store correctly
    def user_params
      params.require(:user).permit(:first_name, :surname, :email, :role_id, :admin, :line_manager)
    end

    def password_params
      params.require(:user).permit(:password, :password_confirmation, :current_password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_password.html.erb
<div class="outer-block">
    <div class="inner-block">

		<h2>Update Password</h2>

			<%= form_for(@user, :url => { :action => "update_password" } ) do |f| %>

			<% if @user.errors.any? %>
			<div id="error_explanation">
			  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h2>

			  <ul>
			  <% @user.errors.full_messages.each do |msg| %>
			    <li><%= msg %></li>
			  <% end %>
			  </ul>
			</div>
			<% end %>

			<div class="field">
			  <%= f.label :current_password %><br />
			  <%= f.password_field :current_password %>
			</div>
			<div class="field">
			  <%= f.label :password, "Password" %><br />
			  <%= f.password_field :password, :autocomplete => "off"  %>
			</div>
			<div class="field">
			  <%= f.label :password_confirmation %><br />
			  <%= f.password_field :password_confirmation %>
			</div>

			<div class="action_container">
			  <%= f.submit 'Update Password', class: "nav_button" %>
			  <%= link_to 'Cancel', @user, class: "nav_button" %>
			</div>
			<% end %>


	</div>
</div>

app/views/users/index.html.erb
<%#This is the index of users that only admin can view, here they choose to view, edit or delete a user %>
<div class="outer-block">
  <div class="inner-block">

    <h2>User Index</h2>

      <%= search_form_for @search, url: users_path do |f| %>

      <%= f.label :surname_cont, "Search by Surname" %>
      <%= f.search_field :surname_cont %>

      <%= f.label :first_name_cont, "Search by First Name" %>
      <%= f.search_field :first_name_cont %>

      <div class="actions"><%= f.submit "Search", class: "nav_button" %></div>

    <% end %>

    <div id='users'>

      <table>
        <thead>
          <tr>
            <th><%= sort_link(@search, :first_name) %></th>
            <th><%= sort_link(@search, :surname) %></th>
            <th>Job Role</th>
            <th>Email</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.surname %></td>
              <td><%= user.role.role_name %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Profile', user %></td>
              <td><% if current_user != user %>
                    <%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% else %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/users/linemanager_skill_search.html.erb
<!DOCTYPE HTML>
<html lang="en">

<div class="outer-block">
  <div class="inner-block">    

    <h2>linemanager skill search</h2>


	<%= search_form_for @q , url: linemanager_skill_search_users_path do |f| %>

	    <strong><%= f.label :user_skills_skill_id_eq, "Search by Skill" %></strong><br>
	    <%= f.select :user_skills_skill_id_eq, options_from_collection_for_select(Skill.all, "id", "skill_name", @q.user_skills_skill_id_eq) %><br><br>
	    
	    <strong><%= f.label :user_skills_skill_level_eq, 'Required Skill Level' %></strong><br>
		<% UserSkill::SKILL_LEVEL.each do |skill_level| %>		  
		  <%= f.check_box(:user_skills_skill_level_cont_any, { :multiple => true }, skill_level, nil) %>
		  <%= f.label :user_skills_skill_level_cont_any, skill_level %><br>
		<% end %><br>
		
		<strong><%= f.label :user_skills_skill_level_eq, 'Date Last Used' %></strong><br>
		<% UserSkill::SKILL_AGE.each do |skill_age| %>
		  <%= f.check_box(:user_skills_date_last_used_cont_any, { :multiple => true }, skill_age, nil) %>
		  <%= f.label :user_skills_date_last_used_cont_any, skill_age %><br>
		<% end %>

	    <div class="actions"><%= f.submit "Search", class: "nav_button" %></div>

	<% end %><br>

	  <table>
        <thead>
          <tr>
            <th><%= sort_link(@q, :first_name) %></th>
            <th><%= sort_link(@q, :surname) %></th>
            <th>Proficiency</th>
            <th>Date Last Used</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>

          	<% @skill2 = UserSkill.find_by(:skill_id => @skill_id, :user_id => user.id)  %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.surname %></td>
              <td><%= @skill2.skill_level if @skill2 %></td>
              <td><%= @skill2.date_last_used if @skill2 %></td>
            </tr>

          <% end %>
        </tbody>
      </table>

  </div>
</div>
</html>

app/views/users/linemanager_team.html.erb
<div class="outer-block">
  <div class="inner-block">

    <h2>Your Team</h2>

    <div id='linemanaged_team'>

      <table>
        <thead>
          <tr>
            <th>First Name</th>
            <th>Surname</th>
            <th>Job Role</th>
            <th>Email</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @linemanaged_team.each do |linemanaged_team| %>
            <tr>
              <td><%= linemanaged_team.first_name %></td>
              <td><%= linemanaged_team.surname %></td>
              <td><%= linemanaged_team.role.role_name %></td>
              <td><%= linemanaged_team.email %></td>
              <td><%= link_to 'View Profile', linemanaged_team, class: "nav_button" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<%#This displays the user profile %>

<div class="outer-block">
  <div class="inner-block">

  	<% if current_user == @user %>

      <h2>My Profile</h2>

    <% else %>

      <h2><%="#{@user.first_name} #{@user.surname}'s Profile"%></h2>

    <% end %>

	  <p>
  		<strong>Name:</strong>
  		<%= @user.first_name %> <%= @user.surname %>
	  </p>

    <p>
      <strong>Job Role:</strong>
      <%= @user.role.role_name if @user.role.role_name?  %>
    </p>

	  <p>
  		<strong>Email:</strong>
  		<%= @user.email %>
	  </p>

    <p>
      <strong>Linemanager:</strong>
      <% @linemanaged_by = UsersLinemanager.find_by(:user_id => @user.id)%>
      <% if @linemanaged_by%>
      <% @linemanager = Linemanager.find_by(:user_id => @linemanaged_by.linemanager_id) %>
      <%= "Linemanaged by #{@linemanager.user.first_name} #{@linemanager.user.surname}"  %>
      <% else %>
      <% end %>
    </p>

    <% if current_user == @user %>

      <%= link_to "Edit Profile", edit_user_registration_path, class: "nav_button" %>

      <%= link_to "Change Password", edit_password_user_path(@user), class: "nav_button" %>

      <%= link_to "My Skills", user_user_skills_path(@user.id), class: "nav_button" %>

      <%= link_to "My Development Activities", user_dev_activities_path(@user), class: "nav_button" %>

    <% else %>

      <%= link_to "#{@user.first_name} #{@user.surname}'s Skills", user_user_skills_path(@user.id), class: "nav_button" %>

      <%= link_to "#{@user.first_name} #{@user.surname}'s Development Activities", user_dev_activities_path(@user), class: "nav_button" %>

    <% end %>
    
  </div>
</div>

app/views/users/user_dev_activities.html.erb
<%#This is the display of dev activities which appears on the user profile - uses the user id of the profile to pull the dev activities %>
<div class="outer-block">
    <div class="inner-block">

      <% if current_user == @user %>

		<h2><%="My Development Activities"%>/h2>

		<p>
			<%= link_to('Add Development Activity', new_user_dev_activity_path(@user), class: "nav_button") %>

			<%= link_to "My Skills", user_user_skills_path(@user), class: "nav_button" %>
		</p>

	  <% else %>

	    <h2><%="#{@user.first_name} #{@user.surname}'s Development Activities"%></h2>

		<p>
			<%= link_to "#{@user.first_name} #{@user.surname}'s Skills", user_user_skills_path(@user), class: "nav_button" %>
		</p>

	  <% end %>

		<table>
			<tr>
				<th>Activity Type</th>
				<th>Development Subject</th>
				<th>Date Completed</th>
				<th>Time Taken</th>
				<th>Key Learning Points</th>
			</tr>

			<% @user.dev_activities.each do |dev_activity| %>
			<tr>
				<td><%= dev_activity.dev_type %></td>
				<td><%= dev_activity.development_subject %></td>
				<td><%= l dev_activity.activity_completed_at if dev_activity.activity_completed_at?  %></td>
				<td><%= dev_activity.time_taken %></td>
				<td><%= dev_activity.key_learning_point %></td>
			</tr>
			<% end %>
				
		</table>

	</div>
</div>