config/routes.rb
DevelopmentActivityApp::Application.routes.draw do

  resources :skill_groups

  resources :users_linemanagers

  resources :role_skills

  resources :dev_activities

  resources :roles do 
    resources :role_skills
  end

  resources :user_skills

  get "pages/AdminDashboard"
  get "pages/LineManagerDashboard"

  resources :skills

  get "mainpage/index"
  root :to => "mainpage#index"

  devise_for :users,
            :controllers => {:registrations => "my_devise/registrations"}

  resources :users do

    collection do
      get 'linemanager_team'
      match 'linemanager_skill_search' => 'users#linemanager_skill_search', via: [:get, :post], as: :linemanager_skill_search
    end

    resources :dev_activities

    resources :user_skills

    resources :linemanagers

    resources :users_linemanagers do
        collection do
          get 'user_search'
        end
    end

    patch 'update_password', on: :collection
    get 'edit_password', on: :member

  end

end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
	belongs_to :skill 
	belongs_to :user

	SKILL_LEVEL = ['None', 'Basic', 'Proficient', 'Expert']

	SKILL_AGE = ['0 - 6 Months', '6 - 12 Months', 'Over 1 Year', 'Over 2 Years']
	
end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user_skill, only: [:show, :edit, :update, :destroy]

  # GET /user_skills
  # GET /user_skills.json
  def index
    @user = User.find(params[:user_id])
    @user_skill = UserSkill.all
  end

  # GET /user_skills/1
  # GET /user_skills/1.json
  def show
    @user_skill = UserSkill.find(params[:id])
    @user = User.find(@user_skill.user_id)
  end

  # GET /user_skills/new
  def new
    @user = current_user
    @user_skill = @user.user_skills.build
  end

  # GET /user_skills/1/edit
  def edit
  end

  # POST /user_skills
  # POST /user_skills.json
  def create
    @user_skill = UserSkill.new(user_skill_params)

    respond_to do |format|
      if @user_skill.save
        format.html { redirect_to user_user_skills_path(current_user), notice: 'User skill was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @user_skill }
      else
        format.html { render action: 'new' }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_skills/1
  # PATCH/PUT /user_skills/1.json
  def update
    respond_to do |format|
      if @user_skill.update(user_skill_params)
        format.html { redirect_to user_user_skills_path(current_user), notice: 'User skill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_skills/1
  # DELETE /user_skills/1.json
  def destroy
    @user_skill.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_skill
      @user_skill = UserSkill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_skill_params
      params.require(:user_skill).permit(:skill_id, :skill_level, :user_id, :date_last_used)
    end
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/views/user_skills/_form.html.erb
<%= form_for([@user, @user_skill]) do |f| %>
  <% if @user_skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_skill.errors.count, "error") %> prohibited this user_skill from being saved:</h2>

      <ul>
      <% @user_skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :skill_name, 'Skill Name' %><br />
    <%= select("user_skill", "skill_id", Skill.all.collect {|p| [p.skill_name, p.id]}, {:include_blank => false}) %>
  </div>

  <div>
    <%= f.label :skill_level, 'Skill Level' %><br />
    <%= f.select(:skill_level, UserSkill::SKILL_LEVEL, :include_blank => true, class: 'form_field')  %>
  </div>

  <div>
    <%= f.label :date_last_used, 'Skill Last Used' %><br />
    <%= f.select(:date_last_used, UserSkill::SKILL_AGE, :include_blank => true, class: 'form_field')  %>
  </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit "Confirm", class: "nav_button" %>
    <%= link_to "Cancel", user_path(@user), class: "nav_button" %>
  </div>
<% end %>

app/views/user_skills/edit.html.erb
<div class="outer-block">
  <div class="inner-block">

	<h2>Edit your skill</h2>

	<%= render 'form' %>

  </div>
 </div>

app/views/user_skills/index.html.erb
<div class="outer-block">
  <div class="inner-block">

    <% if current_user == @user %>

      <h2>My Skills</h2>
      <p>
        <%= link_to('Add Skill', new_user_user_skill_path(@user), class: "nav_button") %> 

        <%= link_to "My Development Activities", user_dev_activities_path(@user), class: "nav_button" %>
      </p>

    <% else %>

      <h2><%="#{@user.first_name} #{@user.surname}'s Skills"%></h2>

      <p>  
        <%= link_to "#{@user.first_name} #{@user.surname}'s Development Activities", user_dev_activities_path(@user), class: "nav_button" %>
      </p>

    <% end %>

    <div id='user_skills'>

      <table>
        <thead>
          <tr>
            <th>Skill Name</th>
            <th>Skill Level</th>
            <th>Skill Last Used</th>
          </tr>
        </thead>

        <tbody>
          <% @user.user_skills.each do |user_skill| %>
            <tr>

              <td><%= user_skill.skill.skill_name %></td>

              <td><%= user_skill.skill_level %></td>

              <td><%= user_skill.date_last_used %></td>

              <td><% if current_user == @user %>
                    <%= link_to 'Edit', edit_user_user_skill_path(@user, user_skill) %>
                  <% else %>
                  <% end %>
              </td>

            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/user_skills/new.html.erb
<div class="outer-block">
  <div class="inner-block">

	<h2>Add Skill</h2>

	<%= render 'form' %>

  </div>
 </div>

app/views/user_skills/show.html.erb
<p id="notice"><%= notice %></p>