config/routes.rb
DevelopmentActivityApp::Application.routes.draw do

  resources :skill_groups

  resources :users_linemanagers

  resources :role_skills

  resources :dev_activities

  resources :roles do 
    resources :role_skills
  end

  resources :user_skills

  get "pages/AdminDashboard"
  get "pages/LineManagerDashboard"

  resources :skills

  get "mainpage/index"
  root :to => "mainpage#index"

  devise_for :users,
            :controllers => {:registrations => "my_devise/registrations"}

  resources :users do

    collection do
      get 'linemanager_team'
      match 'linemanager_skill_search' => 'users#linemanager_skill_search', via: [:get, :post], as: :linemanager_skill_search
    end

    resources :dev_activities

    resources :user_skills

    resources :linemanagers

    resources :users_linemanagers do
        collection do
          get 'user_search'
        end
    end

    patch 'update_password', on: :collection
    get 'edit_password', on: :member

  end

end

app/models/skill_group.rb
class SkillGroup < ActiveRecord::Base

  has_many :skills

end

app/controllers/skill_groups_controller.rb
class SkillGroupsController < ApplicationController
  before_action :set_skill_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @skill_groups = SkillGroup.all
    respond_with(@skill_groups)
  end

  def show
    respond_with(@skill_group)
  end

  def new
    @skill_group = SkillGroup.new
    respond_with(@skill_group)
  end

  def edit
  end

  def create
    @skill_group = SkillGroup.new(skill_group_params)
    @skill_group.save
    respond_with(@skill_group)
  end

  def update
    @skill_group.update(skill_group_params)
    respond_with(@skill_group)
  end

  def destroy
    @skill_group.destroy
    respond_with(@skill_group)
  end

  private
    def set_skill_group
      @skill_group = SkillGroup.find(params[:id])
    end

    def skill_group_params
      params[:skill_group]
    end
end

app/helpers/skill_groups_helper.rb
module SkillGroupsHelper
end

app/views/skill_groups/_form.html.erb
<%= simple_form_for(@skill_group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/skill_groups/edit.html.erb
<h1>Editing skill_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill_group %> |
<%= link_to 'Back', skill_groups_path %>

app/views/skill_groups/index.html.erb
<h1>Listing skill_groups</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @skill_groups.each do |skill_group| %>
      <tr>
        <td><%= link_to 'Show', skill_group %></td>
        <td><%= link_to 'Edit', edit_skill_group_path(skill_group) %></td>
        <td><%= link_to 'Destroy', skill_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill group', new_skill_group_path %>

app/views/skill_groups/new.html.erb
<h1>New skill_group</h1>

<%= render 'form' %>

<%= link_to 'Back', skill_groups_path %>

app/views/skill_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_skill_group_path(@skill_group) %> |
<%= link_to 'Back', skill_groups_path %>